[project]
name = "vzlotn-ae-1-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chardet>=5.2.0",
    "dotenv>=0.9.9",
    "jinja2>=3.1.6",
    "openai>=2.11.0",
    "ruff>=0.14.9",
    "streamlit>=1.52.1",
]
